name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"

    - name: Install Git LFS
      run: |
        git lfs install

    - name: Track MP3 files with Git LFS
      run: |
        git lfs track "*.mp3"
        git add .gitattributes
        git add songs/*.mp3
        git commit -m "Track MP3 files with Git LFS" || echo "No changes to commit"

    - name: Pull latest changes
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_SPACE: ${{ secrets.HF_SPACE }}
        HF_USERNAME: ${{ secrets.HF_USERNAME }}
      run: |
        git pull https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE}.git main --rebase

    - name: Push LFS objects
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_SPACE: ${{ secrets.HF_SPACE }}
        HF_USERNAME: ${{ secrets.HF_USERNAME }}
      run: |
        git config lfs.allowincompletepush true
        git lfs push --all https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE}.git

    - name: Push remaining changes
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_SPACE: ${{ secrets.HF_SPACE }}
        HF_USERNAME: ${{ secrets.HF_USERNAME }}
      run: |
        git add .
        git commit -m "Deploy update via GitHub Actions" || echo "No changes to commit"
        git push https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE}.git HEAD:main